# Generated by Django 3.1.6 on 2021-12-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='numero',
        ),
    ]
