# Generated by Django 3.1.6 on 2021-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_remove_patient_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='numero',
            field=models.FloatField(default=None),
        ),
    ]
