# Generated by Django 3.1.6 on 2022-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20220224_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.CharField(blank=True, default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='BirthDate',
            field=models.DateField(blank=True, default='0000-00-00 '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CNI_number',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email_address',
            field=models.CharField(blank=True, default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LastName',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone_number',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
