# Generated by Django 3.2.9 on 2021-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20211224_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CNI_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
