# Generated by Django 3.2.9 on 2021-12-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_patient_cni_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='number',
        ),
    ]
