# Generated by Django 3.1.6 on 2021-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20211208_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
