# Generated by Django 3.2.9 on 2021-12-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20211224_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
