# Generated by Django 3.2.9 on 2022-05-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20220513_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='allergy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='arterialpressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultation_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='idPatient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='previous_history',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='skin_appearence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
