# Generated by Django 3.1.6 on 2021-12-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_auto_20211208_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
