# Generated by Django 3.2.9 on 2021-12-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultationDate',
            field=models.DateField(auto_now=True),
        ),
    ]
