# Generated by Django 3.1.6 on 2021-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_auto_20211208_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='condition',
            field=models.CharField(choices=[('NoCritical', 'NoCritical'), ('Critical', 'Critical')], default='NoCritical', max_length=50),
        ),
    ]
