# Generated by Django 3.2.9 on 2021-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_auto_20211224_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='status',
            field=models.CharField(default='invalid', max_length=20),
        ),
    ]
