# Generated by Django 3.2.9 on 2022-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_drog_exam_alter_avoir1_id_alter_avoir2_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sentStatus',
            field=models.CharField(default='notSent', max_length=50),
        ),
        migrations.AlterField(
            model_name='drog',
            name='medecineName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examName',
            field=models.CharField(max_length=100),
        ),
    ]
