# Generated by Django 3.1.6 on 2021-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_auto_20211208_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Service',
            field=models.CharField(choices=[('Dental', 'Dental'), ('General Medecine', 'General Medecine'), ('Opthalmogical', 'Opthalmogical'), ('Pediatric', 'pediatric')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
