# Generated by Django 3.2.9 on 2022-01-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_medicament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='status',
            field=models.CharField(default='invalid', max_length=20),
        ),
    ]
