# Generated by Django 3.2.9 on 2022-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_auto_20220615_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='ExamResult',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
