# Generated by Django 3.1.6 on 2022-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0011_auto_20220129_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(default='invalid', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='invalid', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ConsultationCost',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Service',
            field=models.CharField(choices=[('Generalist', 'Generalist'), ('Specialist', 'Specialist')], max_length=50, null=True),
        ),
    ]
