# Generated by Django 3.1.6 on 2022-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0013_auto_20220131_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
