# Generated by Django 3.1.6 on 2022-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0014_consultation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='Date',
        ),
        migrations.AlterField(
            model_name='examen',
            name='ExamCost',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='ExamDescription',
            field=models.CharField(choices=[('blood', 'blood'), ('urine', 'urine'), ('salive', 'salive'), ('selle', 'selle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ConsultationCost',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
